# Generated by Django 5.2.7 on 2025-10-25 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=35)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=35)),
                ('valor', models.PositiveBigIntegerField()),
                ('registrados', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('url', models.ManyToManyField(to='core.imagenevento')),
            ],
        ),
    ]
