# Generated by Django 5.2.7 on 2025-10-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='url',
            new_name='imagenes',
        ),
    ]
