# Generated by Django 5.2.7 on 2025-10-25 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_url_evento_imagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='evento',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagenevento',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='valor',
            field=models.PositiveIntegerField(),
        ),
    ]
