# Generated by Django 5.2.7 on 2025-10-25 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_evento_imagenes_evento_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento'),
        ),
    ]
