# Generated by Django 5.2.7 on 2025-10-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_imagenevento_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagenPrincipal',
            field=models.URLField(default='', max_length=300),
        ),
    ]
