# Generated by Django 5.2.7 on 2025-10-25 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evento_imagenprincipal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='registrados',
            field=models.ManyToManyField(blank=True, related_name='eventos_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
